spring:
  application.name: "Mariadb test application"

  datasource:
    url: jdbc:h2:mem:springbootdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-nam: org.h2.Driver

  jpa.hibernate:
    use-new-id-generator-mappings: true
    ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
management.security.enabled: false
server:
  port: 8100
---

spring:
  profiles: production
  datasource:
    url: ${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-nam: ${DB_DRIVER}

  jpa.properties.hibernate.dialect: ${DB_DIALECT}

  rabbitmq:
    host: ${RABBITMQ_HOST}

server:
  port: 80

