apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: spring-boot-app
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: spring-boot-app
        tier: web
    spec:
      containers:
        - image: @docker.image.prefix@/spring-boot-app:@project.version@
          name: spring-boot-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: mariadb-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: DB_URI
              value: jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
            - name: DB_USER
              value: ${MYSQL_USER}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: MYSQL_PASSWORD
            - name: DB_DRIVER
              value: org.mariadb.jdbc.Driver
            - name: DB_DIALECT
              value: org.hibernate.dialect.MySQL5InnoDBDialect
