#apiVersion: autoscaling/v2alpha1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: cassandra-application
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1beta1
#    kind: Deployment
#    name: cassandra-application
#  minReplicas: 1
#  maxReplicas: 4
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      targetAverageUtilization: 75
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-application
  labels:
    app: cassandra-application
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 80
  selector:
    app: cassandra-application
    tier: web
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cassandra-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-application
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: cassandra-application
        tier: web
    spec:
      containers:
        - image: @docker.image.prefix@/cassandra-application:@project.version@
          name: cassandra-application
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: mongodb-env
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra Cluster"
            - name: CASSANDRA_CONTACT_POINT
              value: "cassandra"
            - name: CASSANDRA_KEYSPACE_NAME
              value: "test"
            - name: RABBITMQ_HOST
              value: rabbitmq
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 3