apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: sql
spec:
  ports:
    - port: 3306
      name: mariadbsql
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MYSQL_PASSWORD: c2VjcmV0
  MYSQL_ROOT_PASSWORD: cm9vdGRic2VjcmV0
  WSREP_SST_PASSWORD: c3N0c2VjcmV0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  MYSQL_USER: dbuser
  MYSQL_DATABASE: mydb
  WSREP_SST_USER: sst
  GALERA_CLUSTER: galera
  MYSQL_INITDB_SKIP_TZINFO: "yes"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: mariadb
  replicas: 3
  template:
    metadata:
      labels:
        app: mariadb
        tier: sql
    spec:
      containers:
        - image: @docker.image.prefix@/mariadb:@project.version@
          name: mariadb
          ports:
            - containerPort: 3306
              name: mysql
            - containerPort: 4444
              name: sst
            - containerPort: 4567
              protocol: TCP
              name: replication-tcp
            - containerPort: 4567
              protocol: UDP
              name: replication-udp
            - containerPort: 4568
              name: ist
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: WSREP_SST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: WSREP_SST_PASSWORD
          envFrom:
            - configMapRef:
                name: mariadb-config
          readinessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 30
            timeoutSeconds: 5
          command: ["/bin/bash", "-c", "docker-entrypoint.sh mysqld"]
  volumeClaimTemplates:
    - metadata:
        name: db-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
