apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: sql
spec:
  ports:
    - port: 3306
      name: mariadbsql
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MYSQL_PASSWORD: c2VjcmV0
  MYSQL_ROOT_PASSWORD: cm9vdGRic2VjcmV0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  MYSQL_USER: dbuser
  MYSQL_DATABASE: mydb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-conf-d
data:
  charset.cnf: |
    [client]
    default-character-set = utf8

    [mysqld]
    character-set-server  = utf8
    collation-server      = utf8_unicode_ci
    character_set_server  = utf8
    collation_server      = utf8_general_ci
  mysqld_safe_syslog.cnf: |
    [mysqld_safe]
    skip_log_error
    syslog
  galera.cnf: |
    [galera]
    wsrep_sst_method = xtrabackup-v2
    # This can be insecure, because the user is only available via localhost
    # We should still try to integrate it with Kubernetes secrets
    wsrep_sst_auth=xtrabackup_sst:xtrabackup_sst
    default_storage_engine = innodb
    binlog_format = row
    innodb_autoinc_lock_mode = 2
    innodb_flush_log_at_trx_commit = 0
    query_cache_size = 0
    query_cache_type = 0
    wsrep_provider=/usr/lib/galera/libgalera_smm.so

    # By default every node is standalone
    wsrep_cluster_address=gcomm://
    wsrep_cluster_name=galera
    wsrep_node_address=127.0.0.1
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: mariadb
  replicas: 2
  template:
    metadata:
      labels:
        app: mariadb
        tier: sql
    spec:
      initContainers:
        - name: setup-mysql-config
          image: alpine
          command: ["/bin/sh", "-c", "
            set -ex\n
            rm -Rf /conf/mariadb/*\n
            cp -aL /conf/mariadb-template/*.cnf /conf/mariadb/\n
            export MY_NAME=`hostname -f`\n
            sed -i -e \"s|^wsrep_node_address=.*$|wsrep_node_address=${MY_NAME}|\" /conf/mariadb/galera.cnf\n
            export CLUSTER_NAME=`hostname -d | tr '.' '\n' | head -1`\n
            sed -i -e \"s|^wsrep_cluster_name=.*$|wsrep_cluster_name=${CLUSTER_NAME}|\" /conf/mariadb/galera.cnf\n
            export NODE_BASE_NAME=`hostname | tr '-' '\n' | head -1`\n
            export NODE_ID=`hostname | tr '-' '\n' | tail -1`\n
            export DOMAIN=`hostname -d`\n
            export NODES=`for i in \\`seq 0 ${NODE_ID}\\`; do echo $NODE_BASE_NAME-$i.$DOMAIN; done | head -n -1 | tr '\n' ',' | cut -c1- | rev | cut -c2- | rev`\n
            sed -i -e \"s|^wsrep_cluster_address=.*$|wsrep_cluster_address=gcomm://${NODES}|\" /conf/mariadb/galera.cnf\n
          "]
          volumeMounts:
            - name: db-config-storage
              mountPath: /conf/mariadb
            - name: mariadb-conf-d
              mountPath: /conf/mariadb-template
      containers:
        - image: mariadb:10.1
          name: mariadb
          ports:
            - containerPort: 3306
              name: mysql
            - containerPort: 4444
              name: sst
            - containerPort: 4567
              name: replication
            - containerPort: 4568
              name: ist
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/mysql
            - name: db-config-storage
              mountPath: /etc/mysql/conf.d
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: MYSQL_ROOT_PASSWORD
          envFrom:
            - configMapRef:
                name: mariadb-config
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'show databases;'"]
            initialDelaySeconds: 15
            timeoutSeconds: 45
          args: ["mysqld", "--wsrep-on"]
      volumes:
        - name: mariadb-conf-d
          configMap:
            name: mariadb-conf-d
  volumeClaimTemplates:
    - metadata:
        name: db-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: db-config-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Mi
