#apiVersion: autoscaling/v2alpha1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: mongo-application
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1beta1
#    kind: Deployment
#    name: mongo-application
#  minReplicas: 1
#  maxReplicas: 4
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      targetAverageUtilization: 75
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-application
  labels:
    app: mongo-application
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 80
  selector:
    app: mongo-application
    tier: web
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-application
      tier: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: mongo-application
        tier: web
    spec:
      containers:
        - image: @docker.image.prefix@/mongo-application:@project.version@
          name: mongo-application
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: mongodb-env
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: MONGO_AUTHENTICATION_DATABASE
              value: ${MONGO_ADMIN_DATABASE}
            - name: MONGO_URI
              value: mongodb://${MONGO_ADMIN_USER}:$(MONGO_PASSWORD)@${MONGO_HOST}/testdb?replicaSet=${MONGO_RS}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_ADMIN_PASSWORD
            - name: RABBITMQ_HOST
              value: rabbitmq
