spring:
  datasource:
    url: jdbc:h2:mem:springbootdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverclassName: org.h2.Driver

  jpa.hibernate.ddl-auto: create-drop
---

spring:
    profiles: production
    datasource:
        url: ${DB_URI}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driverclassName: ${DB_DRIVER}

    jpa:
        properties:
            hibernate:
                dialect: ${DB_DIALECT}