apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
  labels:
    app: @project.artifactId@
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8080
  selector:
    app: @project.artifactId@
    tier: web
  type: LoadBalancer
