apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
  labels:
    app: @project.artifactId@
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8080
  selector:
    app: @project.artifactId@
    tier: web
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: @project.artifactId@
spec:
  replicas: 3
  selector:
    matchLabels:
      app: @project.artifactId@
      tier: web
  template:
    metadata:
      labels:
        app: @project.artifactId@
        tier: web
    spec:
      containers:
        - image: @docker.image.prefix@/@project.artifactId@:@project.version@
          name: @project.artifactId@
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: DB_URI
              value: jdbc:mariadb://mariadb:3306/mydb
            - name: DB_USER
              value: dbuser
            - name: DB_PASSWORD
              value: secret
            - name: DB_DRIVER
              value: org.mariadb.jdbc.Driver
            - name: DB_DIALECT
              value: org.hibernate.dialect.MySQL5InnoDBDialect
