apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    app: mariadb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /var/lib/kubernetes/data/pv-1
