apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    tier: sql
spec:
  ports:
    - port: 3306
      name: mariadbsql
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MYSQL_PASSWORD: c2VjcmV0
  MYSQL_ROOT_PASSWORD: cm9vdGRic2VjcmV0
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        tier: sql
    spec:
      containers:
        - image: mariadb:10.1
          name: mariadb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/mysql
            - name: db-config-storage
              mountPath: /conf/mysql
          env:
            - name: MYSQL_USER
              value: dbuser
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: mydb
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'show databases;'"
            initialDelaySeconds: 15
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: db-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: db-config-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Mi
