spring:
  application.name: "Mongo test application"

  rabbitmq:
    host: localhost
    port: 5672
management.security.enabled: false
server:
  port: 8090
---
spring:
  profiles: production

  rabbitmq:
    host: ${RABBITMQ_HOST}
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}

server:
  port: 80
