spring:
  application.name: "Mongo test application"

  rabbitmq:
    host: localhost
    port: 5672
management.security.enabled: false
server:
  port: 8090
---
spring:
  profiles: production

  rabbitmq:
    host: ${RABBITMQ_HOST}
server:
  port: 80
